name: Artifacts 

on:  workflow_dispatch

jobs:
  job_1:
    name: Upload Artifact
    runs-on: ubuntu-latest
    
    steps:
      - name: "Create a local file"
        run: echo "Hi, "Tech IT Factory" is a cutting-edge e-learning platform specializing in the delivery of IT and technology-based courses. Driven by a passion for technology and education, the company aims to bridge the gap between the rapidly evolving tech world and enthusiastic learners globally." > about-tif.txt
      
      - uses: actions/upload-artifact@v3

        with:
          name: about-tif
          path: about-tif.txt
          retention-days: 1

 
  job_2:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: about-tif
      - name: Printing the about-tif content
        run: cat about-tif.txt