name: 'Custom Env Vars'
on:
  workflow_dispatch:
  
env:
  DAY_OF_WEEK: Techday
  testvar: value-global

jobs: 
  mainjob:
    name: 'Print the env vars'
    runs-on: ubuntu-latest

    env:
      Greeting: Hello
#      testvar: value-job
    
    steps:
    - name: print-values-of-env-vars
      run: |
        echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        echo "testvar  $testvar"
        echo "testvar  ${{ env.testvar }}"
#      env:
#          First_Name: Subscribers
#          testvar: value-step