name: Deploy EKS using Terraform
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Adjust to your preferred AWS region

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        cd .github/workflows/EKS
        terraform init

    - name: Terraform Plan
      run: |
        cd .github/workflows/EKS
        terraform plan -no-color
      continue-on-error: true

    - name: Terraform Apply
      run: |
        cd .github/workflows/EKS
        terraform apply -auto-approve
