name: GitHub Environments

on:
  workflow_dispatch:

jobs:
  deployment:
    
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://prod.tif.com
      
      
    steps:
      - name: 'Print secret from environment'
        run: |
            echo "APP_SECRET: ${{ secrets.PROD_APP_SECRET  }}"
            echo "APP_SECRET: ${{ secrets.APP_SECRET  }}"