name: 'custom GITHUB_ENV var'

on:  workflow_dispatch

jobs:
  custom_GITHUB_ENV:
    runs-on: ubuntu-latest 
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=TechITFactory" >> $GITHUB_ENV

    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" 